# Generated by Django 2.2.4 on 2019-10-21 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_auto_20191021_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing1',
            name='sent_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 21, 5, 29, 40, 457229)),
        ),
    ]
