# Generated by Django 2.2.4 on 2019-10-24 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_auto_20191021_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing1',
            name='sent_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 24, 4, 51, 17, 787585)),
        ),
    ]
