# Generated by Django 2.2.4 on 2019-10-30 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_auto_20191030_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing1',
            name='sent_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 30, 2, 57, 20, 369467)),
        ),
    ]
