# Generated by Django 2.2.4 on 2019-11-18 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_auto_20191031_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_count', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.CharField(max_length=250)),
                ('user_id', models.IntegerField()),
                ('timestamp', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='outgoing1',
            name='sent_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 18, 5, 46, 44, 771050)),
        ),
    ]
