# Generated by Django 2.2.4 on 2019-12-03 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_auto_20191125_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='outgoing1',
            name='sent_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 12, 3, 7, 7, 47, 269116)),
        ),
    ]
