# Generated by Django 2.2.4 on 2020-01-27 11:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('sms', '0021_auto_20191219_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='oc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='outgoing1',
            name='oc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='outgoing2',
            name='oc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='outgoingdone',
            name='oc',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CustomerSubAccounts',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Customer', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Sub Account',
                'verbose_name_plural': 'Sub Accounts',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
