# Generated by Django 2.2.4 on 2020-02-20 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0023_tobentotill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='access_code',
            field=models.CharField(default='ROBERMS_LTD', max_length=11),
        ),
        migrations.CreateModel(
            name='OutgoingNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='68124233232', max_length=50)),
                ('access_code', models.CharField(default='ROBERMS_LTD', max_length=50)),
                ('phone_number', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Customer')),
            ],
            options={
                'verbose_name': 'OutgoingNew',
                'verbose_name_plural': 'OutgoingsNew',
            },
        ),
        migrations.CreateModel(
            name='OutgoingApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='6019542000169037', max_length=50)),
                ('unique_identifier', models.CharField(max_length=250, null=True)),
                ('access_code', models.CharField(default='725701', max_length=50)),
                ('dest_msisdn', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Customer')),
            ],
            options={
                'verbose_name': 'OutgoingApi',
                'verbose_name_plural': 'OutgoingApis',
            },
        ),
    ]
