# Generated by Django 2.2.4 on 2020-03-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0027_applicationcontact_inbox_sendernameapplication_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='messages',
            new_name='message',
        ),
        migrations.AddField(
            model_name='inbox',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.Tag'),
            preserve_default=False,
        ),
    ]
