# Generated by Django 2.2.4 on 2020-04-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0030_tag_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='pushed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='customer',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, to='sms.Customer'),
        ),
    ]
