# Generated by Django 2.2.4 on 2020-10-14 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0031_auto_20200422_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.Customer'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.Tag'),
        ),
    ]
