# Generated by Django 2.2.4 on 2020-12-03 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0032_auto_20201014_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
