# Generated by Django 2.2.4 on 2021-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0034_stannpatients'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingnew',
            name='usage_status',
            field=models.BooleanField(default=False),
        ),
    ]
