# Generated by Django 2.2.4 on 2021-07-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0036_auto_20210329_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sender_type',
            field=models.IntegerField(choices=[(1, 'Promotional'), (2, 'Transactional')], default=1),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='sender_type',
            field=models.IntegerField(choices=[(1, 'Promotional'), (2, 'Transactional')], default=1),
        ),
        migrations.AddField(
            model_name='outgoingapi',
            name='sender_type',
            field=models.IntegerField(choices=[(1, 'Promotional'), (2, 'Transactional')], default=1),
        ),
        migrations.AddField(
            model_name='outgoingapinew',
            name='sender_type',
            field=models.IntegerField(choices=[(1, 'Promotional'), (2, 'Transactional')], default=1),
        ),
        migrations.AddField(
            model_name='outgoingdone',
            name='sender_type',
            field=models.IntegerField(choices=[(1, 'Promotional'), (2, 'Transactional')], default=1),
        ),
        migrations.AddField(
            model_name='outgoingnew',
            name='sender_type',
            field=models.IntegerField(choices=[(1, 'Promotional'), (2, 'Transactional')], default=1),
        ),
    ]
