# Generated by Django 3.1.5 on 2021-09-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0038_remove_outgoingdone_sender_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=250)),
                ('msisdn', models.CharField(max_length=250)),
                ('account_number', models.CharField(max_length=250)),
                ('id_num', models.CharField(max_length=250, null=True)),
                ('meter_num', models.CharField(max_length=250, null=True)),
                ('customer_rate', models.CharField(max_length=250, null=True)),
                ('reading_type', models.CharField(max_length=250, null=True)),
                ('last_meter_reading_date', models.CharField(max_length=250, null=True)),
                ('comment', models.EmailField(max_length=250, null=True)),
                ('court', models.CharField(max_length=250, null=True)),
                ('network', models.CharField(max_length=250, null=True)),
                ('previous_reading', models.FloatField(default=0, max_length=250, null=True)),
                ('readings', models.FloatField(default=0, max_length=250, null=True)),
                ('amount_from_units', models.FloatField(default=0, max_length=250, null=True)),
                ('credit', models.FloatField(default=0, max_length=250, null=True)),
                ('arrears', models.FloatField(default=0, max_length=250, null=True)),
                ('amount_due', models.FloatField(default=0, max_length=250, null=True)),
                ('payable', models.FloatField(default=0, max_length=250, null=True)),
                ('confirmed', models.IntegerField(default=0, max_length=250, null=True)),
                ('processed', models.IntegerField(default=0, max_length=250, null=True)),
                ('message', models.IntegerField(default=0, max_length=250, null=True)),
                ('units_consumed', models.FloatField(default=0, max_length=250, null=True)),
                ('last_payment_date', models.CharField(max_length=250, null=True)),
                ('meter_change_date', models.CharField(max_length=250, null=True)),
                ('connection_fee_paid', models.FloatField(default=0, max_length=250, null=True)),
                ('read_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'water_meterreading',
                'verbose_name_plural': 'water_meterreadings',
            },
        ),
        migrations.CreateModel(
            name='WaterClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('client_number', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('kra_pin', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='WaterClientAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=250)),
                ('msisdn', models.CharField(max_length=250)),
                ('client_number', models.CharField(max_length=250)),
                ('id_num', models.CharField(max_length=250, null=True)),
                ('meter_num', models.CharField(max_length=250, null=True)),
                ('customer_rate', models.CharField(max_length=250, null=True)),
                ('connection_fee', models.CharField(max_length=250, null=True)),
                ('last_meter_reading_date', models.CharField(max_length=250, null=True)),
                ('email_address', models.EmailField(max_length=250, null=True)),
                ('court', models.CharField(max_length=250, null=True)),
                ('network', models.CharField(max_length=250, null=True)),
                ('last_meter_reading', models.FloatField(default=0, max_length=250, null=True)),
                ('amount_due', models.FloatField(default=0, max_length=250, null=True)),
                ('units_consumed', models.FloatField(default=0, max_length=250, null=True)),
                ('last_payment_date', models.CharField(max_length=250, null=True)),
                ('meter_change_date', models.CharField(max_length=250, null=True)),
                ('connection_fee_paid', models.FloatField(default=0, max_length=250, null=True)),
                ('message', models.IntegerField(default=0, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Water',
                'verbose_name_plural': 'Waters',
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=250)),
                ('msisdn', models.CharField(max_length=250)),
                ('account_number', models.CharField(max_length=250)),
                ('id_num', models.CharField(max_length=250, null=True)),
                ('meter_num', models.CharField(max_length=250, null=True)),
                ('customer_rate', models.CharField(max_length=250, null=True)),
                ('reading_type', models.CharField(max_length=250, null=True)),
                ('last_meter_reading_date', models.CharField(max_length=250, null=True)),
                ('comment', models.EmailField(max_length=250, null=True)),
                ('court', models.CharField(max_length=250, null=True)),
                ('network', models.CharField(max_length=250, null=True)),
                ('previous_reading', models.FloatField(default=0, max_length=250, null=True)),
                ('readings', models.FloatField(default=0, max_length=250, null=True)),
                ('amount_from_units', models.FloatField(default=0, max_length=250, null=True)),
                ('credit', models.FloatField(default=0, max_length=250, null=True)),
                ('arrears', models.FloatField(default=0, max_length=250, null=True)),
                ('amount_due', models.FloatField(default=0, max_length=250, null=True)),
                ('payable', models.FloatField(default=0, max_length=250, null=True)),
                ('confirmed', models.IntegerField(default=0, max_length=250, null=True)),
                ('processed', models.IntegerField(default=0, max_length=250, null=True)),
                ('message', models.IntegerField(default=0, max_length=250, null=True)),
                ('units_consumed', models.FloatField(default=0, max_length=250, null=True)),
                ('last_payment_date', models.CharField(max_length=250, null=True)),
                ('meter_change_date', models.CharField(max_length=250, null=True)),
                ('connection_fee_paid', models.FloatField(default=0, max_length=250, null=True)),
                ('read_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'water_meterreading',
                'verbose_name_plural': 'water_meterreadings',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sender_type',
        ),
        migrations.RemoveField(
            model_name='managertopup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='managertopup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='sender_type',
        ),
        migrations.RemoveField(
            model_name='outgoingapi',
            name='sender_type',
        ),
        migrations.RemoveField(
            model_name='outgoingapinew',
            name='sender_type',
        ),
        migrations.RemoveField(
            model_name='outgoingnew',
            name='sender_type',
        ),
        migrations.RemoveField(
            model_name='outgoingnew',
            name='usage_status',
        ),
        migrations.CreateModel(
            name='WaterClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.group')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
