# Generated by Django 3.1.5 on 2021-09-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0039_auto_20210909_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sender_Id',
            field=models.CharField(default='ROBERMS', max_length=11),
        ),
    ]
