# Generated by Django 3.1.5 on 2021-08-05 17:43

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('location', models.CharField(max_length=250, null=True)),
                ('phone_number', models.TextField(null=True)),
                ('access_code', models.CharField(default='ROBERMS_LTD', max_length=11)),
                ('service_id', models.CharField(default='6015152000175328', max_length=50)),
                ('business_name', models.CharField(default='Business Name', max_length=100)),
                ('credit', models.FloatField(default=5.0)),
                ('customer_code', models.IntegerField(null=True)),
                ('sender_name', models.CharField(default='Roberms LTD', max_length=250, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='From_Willinya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code', models.IntegerField()),
                ('message_cost', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ManagerTopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_count', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.CharField(max_length=250)),
                ('user_id', models.IntegerField()),
                ('timestamp', models.CharField(max_length=250)),
                ('commission_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField()),
                ('service_id', models.CharField(default='68124233232', max_length=50)),
                ('access_code', models.CharField(default='72345', max_length=50)),
                ('phone_number', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OutgoingDone',
                'verbose_name_plural': 'OutgoingsDone',
            },
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SalesPerson',
                'verbose_name_plural': 'SalesPeople',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sms_TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=250)),
                ('transaction_ref', models.CharField(max_length=250, unique=True)),
                ('amount', models.CharField(max_length=250)),
                ('till_number', models.CharField(max_length=250)),
                ('f_name', models.CharField(max_length=250)),
                ('l_name', models.CharField(max_length=250)),
                ('signature', models.CharField(max_length=250)),
                ('account_no', models.CharField(max_length=250)),
                ('transaction_type', models.CharField(max_length=250)),
                ('verifycode', models.CharField(max_length=250)),
                ('user_id', models.IntegerField()),
                ('verified', models.IntegerField(default=0)),
                ('timestamp', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TobentoTill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_number', models.IntegerField()),
                ('till_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('till_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('transaction_ref', models.IntegerField()),
                ('amount', models.FloatField()),
                ('till_number', models.IntegerField()),
                ('f_name', models.CharField(max_length=250)),
                ('l_name', models.CharField(max_length=250)),
                ('verify_code', models.IntegerField()),
                ('user_id', models.IntegerField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('timestamp', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Till_Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('till', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=250)),
                ('response', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
        ),
        migrations.CreateModel(
            name='StAnnPatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('processed', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.group')),
            ],
        ),
        migrations.CreateModel(
            name='SenderNameApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=11)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.salesperson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='68124233232', max_length=50)),
                ('access_code', models.CharField(default='ROBERMS_LTD', max_length=50)),
                ('phone_number', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'verbose_name': 'OutgoingNew',
                'verbose_name_plural': 'OutgoingsNew',
            },
        ),
        migrations.CreateModel(
            name='OutgoingApiNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='68124233232', max_length=50)),
                ('access_code', models.CharField(default='ROBERMS_LTD', max_length=50)),
                ('phone_number', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('unique_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'verbose_name': 'OutgoingApiNew',
                'verbose_name_plural': 'OutgoingsApiNew',
            },
        ),
        migrations.CreateModel(
            name='OutgoingApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='6019542000169037', max_length=50)),
                ('unique_identifier', models.CharField(max_length=250, null=True)),
                ('access_code', models.CharField(default='725701', max_length=50)),
                ('dest_msisdn', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'verbose_name': 'OutgoingApi',
                'verbose_name_plural': 'OutgoingApis',
            },
        ),
        migrations.CreateModel(
            name='Outgoing2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='68124233232', max_length=50)),
                ('access_code', models.CharField(default='72345', max_length=50)),
                ('phone_number', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'verbose_name': 'Outgoing2',
                'verbose_name_plural': 'Outgoings2',
            },
        ),
        migrations.CreateModel(
            name='Outgoing1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('access_code', models.CharField(max_length=50)),
                ('phone_number', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'verbose_name': 'Outgoing1',
                'verbose_name_plural': 'Outgoing1',
            },
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='68124233232', max_length=50)),
                ('access_code', models.CharField(default='72345', max_length=50)),
                ('phone_number', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'verbose_name': 'Outgoing',
                'verbose_name_plural': 'Outgoings',
            },
        ),
        migrations.CreateModel(
            name='MpesaPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.IntegerField()),
                ('reference_number', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('till_number', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('verified', models.BooleanField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=250)),
                ('processed', models.BooleanField(default=False)),
                ('pushed', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTrackCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track_code', models.CharField(max_length=250)),
                ('number_of_messages', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=250, unique=True)),
                ('status_complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='CustomerSubAccounts',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.customer', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Sub Account',
                'verbose_name_plural': 'Sub Accounts',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.group')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='ApplicationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.sendernameapplication')),
            ],
        ),
    ]
