# Generated by Django 3.1.5 on 2021-09-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_watermeterreadingsraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermeterreadingsraw',
            name='readings',
            field=models.FloatField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
