# Generated by Django 3.1.5 on 2021-09-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_watermeterreadingsraw_readings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watermeterreadingsraw',
            old_name='read_type',
            new_name='reading_type',
        ),
    ]
