# Generated by Django 3.1.5 on 2021-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_auto_20210912_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeterreadingsraw',
            name='readings',
            field=models.FloatField(max_length=250, null=True),
        ),
    ]
