# Generated by Django 3.1.5 on 2021-10-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0020_auto_20211003_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCustomerNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Netowrks',
            },
        ),
        migrations.DeleteModel(
            name='WaterCourter',
        ),
        migrations.AddField(
            model_name='watermeterreplacement',
            name='amount_due',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='watermeterreplacement',
            name='court',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='watermeterreplacement',
            name='names',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
