# Generated by Django 3.1.5 on 2021-10-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0023_waterpaymentreceived_waterpaymentreceivedmanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterpaymentreceived',
            name='comments',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='waterpaymentreceivedmanual',
            name='comments',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
