# Generated by Django 3.1.5 on 2021-10-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0024_auto_20211004_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_charge', models.CharField(max_length=250)),
                ('rate', models.CharField(max_length=250)),
                ('the_changes', models.CharField(max_length=250, null=True)),
                ('user_id', models.CharField(max_length=250, null=True)),
                ('timestamp', models.IntegerField(default=0, max_length=4)),
                ('clients', models.CharField(max_length=250, null=True)),
                ('comments', models.CharField(max_length=250, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
