# Generated by Django 3.1.5 on 2021-10-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0031_wateroutbox_watersmsoutcourt_watersmsoutnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSmsOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=250, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('text_message', models.CharField(max_length=400)),
                ('message_length', models.IntegerField(default=0, null=True)),
                ('deducted_units', models.IntegerField(default=0, null=True)),
                ('processed', models.IntegerField(max_length=250, null=True)),
                ('client', models.IntegerField(null=True)),
                ('out_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'water_sms_out',
            },
        ),
    ]
