# Generated by Django 3.1.5 on 2021-10-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0032_watersmsout'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersmsout',
            name='court',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersmsout',
            name='network',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='watersmsout',
            name='processed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
