# Generated by Django 3.1.5 on 2021-10-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0034_auto_20211011_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateroutbox',
            name='track_code',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
