# Generated by Django 3.1.5 on 2021-10-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0035_wateroutbox_track_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateroutbox',
            name='delivery_status',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
