# Generated by Django 3.1.5 on 2021-08-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roberms_admin', '0001_initial'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.salesperson'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roberms_admin.company'),
        ),
    ]
