# Generated by Django 2.2.4 on 2019-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='sms_topup',
            name='transaction_ref',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
