# Generated by Django 2.2.4 on 2019-10-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20191010_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
