# Generated by Django 2.2.4 on 2019-10-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20191014_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Till_Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('till', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
