# Generated by Django 2.2.4 on 2019-10-30 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_auto_20191025_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing1',
            name='sent_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 10, 30, 2, 44, 3, 987375)),
        ),
    ]
