# Generated by Django 2.2.4 on 2019-11-25 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_auto_20191118_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='managertopup',
            name='commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outgoing1',
            name='sent_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 25, 2, 18, 55, 665362)),
        ),
    ]
