# Generated by Django 2.2.4 on 2019-12-03 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0019_auto_20191203_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing1',
            name='sent_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 12, 3, 7, 17, 22, 36373)),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='commission',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
