# Generated by Django 2.2.4 on 2020-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0024_auto_20200220_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='From_Willinya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code', models.IntegerField()),
                ('message_cost', models.CharField(max_length=250)),
            ],
        ),
    ]
