# Generated by Django 2.2.4 on 2020-03-06 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0025_from_willinya'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingApiNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default='68124233232', max_length=50)),
                ('access_code', models.CharField(default='ROBERMS_LTD', max_length=50)),
                ('phone_number', models.TextField(null=True)),
                ('text_message', models.TextField(max_length=600, null=True)),
                ('track_code', models.CharField(max_length=50, null=True)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=1000, null=True)),
                ('oc', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('request_identifier', models.CharField(max_length=3000, null=True)),
                ('unique_identifier', models.CharField(max_length=3000, null=True)),
                ('extra_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Customer')),
            ],
            options={
                'verbose_name': 'OutgoingApiNew',
                'verbose_name_plural': 'OutgoingsApiNew',
            },
        ),
    ]
