# Generated by Django 2.2.4 on 2020-04-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0029_auto_20200318_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
