# Generated by Django 2.2.4 on 2021-03-29 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0035_outgoingnew_usage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='managertopup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 29, 12, 17, 41, 175539)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managertopup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
