# Generated by Django 2.2.4 on 2021-07-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0037_auto_20210702_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingdone',
            name='sender_type',
        ),
    ]
