# Generated by Django 3.1.5 on 2021-09-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0043_customer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sender_Id',
        ),
    ]
