# Generated by Django 3.1.5 on 2021-09-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_waterclientall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterclientall',
            old_name='in_num',
            new_name='id_num',
        ),
    ]
