# Generated by Django 3.1.5 on 2021-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_waterclientall_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterclientall',
            name='amount_due',
            field=models.FloatField(default=0, max_length=250, null=True),
        ),
    ]
