# Generated by Django 3.1.5 on 2021-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20210908_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterclientall',
            name='connection_fee_paid',
            field=models.FloatField(default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='waterclientall',
            name='last_meter_reading',
            field=models.FloatField(default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='waterclientall',
            name='message',
            field=models.IntegerField(default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='waterclientall',
            name='units_consumed',
            field=models.FloatField(default=0, max_length=250, null=True),
        ),
    ]
