# Generated by Django 3.1.5 on 2021-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_auto_20210908_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterclientall',
            name='email_address',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
