# Generated by Django 3.1.5 on 2021-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_meterreadings_watermeterreadings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeterReadingsRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=250)),
                ('msisdn', models.CharField(max_length=250)),
                ('account_number', models.CharField(max_length=250)),
                ('processed', models.IntegerField(max_length=250, null=True)),
                ('read_type', models.CharField(max_length=250, null=True)),
                ('read_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'water_meterreading_raw',
                'verbose_name_plural': 'water_meterreading_raw',
            },
        ),
    ]
