# Generated by Django 3.1.5 on 2021-09-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_auto_20210912_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeterreadingsraw',
            name='readings',
            field=models.FloatField(default=0, max_length=250, null=True),
        ),
    ]
