# Generated by Django 3.1.5 on 2021-10-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0019_watercustomernetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCourter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Netowrks',
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('last_units', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.waterclientall')),
            ],
        ),
        migrations.DeleteModel(
            name='WaterCustomerNetwork',
        ),
    ]
