# Generated by Django 3.1.5 on 2021-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0027_auto_20211008_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersysconf',
            name='comment',
            field=models.CharField(default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='watersysconf',
            name='rate',
            field=models.FloatField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='watersysconf',
            name='standing_charge',
            field=models.FloatField(max_length=250, null=True),
        ),
    ]
