# Generated by Django 3.1.5 on 2021-10-08 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0028_auto_20211008_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersysconf',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
