# Generated by Django 3.1.5 on 2021-10-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0030_watersysconfhist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterOutbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=250, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('dest_msisdn', models.CharField(default=0, max_length=250, null=True)),
                ('text_message', models.CharField(max_length=400)),
                ('sender_name', models.CharField(max_length=250, null=True)),
                ('client', models.IntegerField(null=True)),
                ('out_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'water_outbox',
                'verbose_name_plural': 'water_outbox',
                'db_table': 'water_outbox',
            },
        ),
        migrations.CreateModel(
            name='WaterSmsOutCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=250, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('network', models.CharField(default=0, max_length=250, null=True)),
                ('text_message', models.CharField(max_length=400)),
                ('processed', models.IntegerField(max_length=250, null=True)),
                ('client', models.IntegerField(null=True)),
                ('out_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'water_outbox_network',
                'verbose_name_plural': 'water_outbox_network',
                'db_table': 'water_sms_out_court',
            },
        ),
        migrations.CreateModel(
            name='WaterSmsOutNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=250, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('network', models.CharField(default=0, max_length=250, null=True)),
                ('text_message', models.CharField(max_length=400)),
                ('processed', models.IntegerField(max_length=250, null=True)),
                ('client', models.IntegerField(null=True)),
                ('out_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'water_outbox_network',
                'verbose_name_plural': 'water_outbox_network',
                'db_table': 'water_sms_out_network',
            },
        ),
    ]
