# Generated by Django 3.1.5 on 2021-10-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0036_wateroutbox_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterclientall',
            name='amount_0',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='waterclientall',
            name='amount_1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='waterclientall',
            name='amount_2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='waterclientall',
            name='amount_3',
            field=models.FloatField(default=0, null=True),
        ),
    ]
