# Generated by Django 3.1.5 on 2021-10-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0037_auto_20211018_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterclientall',
            name='msisdn2',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
