# Generated by Django 3.1.5 on 2021-10-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0038_waterclientall_msisdn2'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterclientall',
            name='meter_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='watermeterreplacement',
            name='meter_number',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
