# Generated by Django 3.1.5 on 2021-10-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0039_auto_20211021_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiwamaMpesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=250, null=True)),
                ('sender_phone', models.CharField(max_length=250)),
                ('trans_id', models.CharField(max_length=100, unique=True)),
                ('processed', models.IntegerField(default=0)),
                ('amount', models.IntegerField(null=True)),
                ('msisdn', models.CharField(default=0, max_length=250, null=True)),
                ('paybill', models.CharField(default=0, max_length=250, null=True)),
                ('account_number', models.CharField(default=0, max_length=250, null=True)),
                ('names', models.CharField(max_length=250, null=True)),
                ('allocated_to', models.CharField(max_length=250, null=True)),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mpesa',
                'verbose_name_plural': 'mpesa',
                'db_table': 'mpesa',
            },
        ),
    ]
