# Generated by Django 3.1.5 on 2021-10-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0040_miwamampesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miwamampesa',
            old_name='create_date',
            new_name='in_date',
        ),
        migrations.AddField(
            model_name='miwamampesa',
            name='is_read',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='miwamampesa',
            name='organizational_balance',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='miwamampesa',
            name='transaction_type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
