# Generated by Django 3.1.5 on 2021-10-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0042_waterpaymentreallocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermeterreadings',
            name='read_by',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
