# Generated by Django 2.2.4 on 2020-12-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roberms_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status_visited',
            field=models.BooleanField(default=False),
        ),
    ]
